// <auto-generated> 由 Tools/ProtoGen 生成，请勿手改。 </auto-generated>
#pragma warning disable
namespace Game.Protocol
{
    public sealed partial class GC2GS_020_001_GetClickerProfileRequest : Framework.Network.IRequest<GS2GC_020_001_GetClickerProfileResponse>
    {
        public byte GetMainId() => 20;
        public byte GetSubId() => 1;
    }

    public sealed partial class GS2GC_020_001_GetClickerProfileResponse : Framework.Network.IResponse
    {
        public byte GetMainId() => 20;
        public byte GetSubId() => 1;
    }

}
