// <auto-generated> 由 Tools/ProtoGen 生成，请勿手改。 </auto-generated>
#pragma warning disable
namespace Game.Protocol
{
    public sealed partial class GC2GS_010_001_GetSampleItemsRequest : Framework.Network.IRequest<GS2GC_010_001_GetSampleItemsResponse>
    {
        public byte GetMainId() => 10;
        public byte GetSubId() => 1;
    }

    public sealed partial class GS2GC_010_001_GetSampleItemsResponse : Framework.Network.IResponse
    {
        public byte GetMainId() => 10;
        public byte GetSubId() => 1;
    }

}
