// <auto-generated> 由 Tools/ProtoGen 生成，请勿手改。 </auto-generated>
#pragma warning disable
namespace Game.Protocol
{
    public sealed partial class GC2GS_001_001_HeartbeatRequest : Framework.Network.IRequest<GS2GC_001_001_HeartbeatResponse>
    {
        public byte GetMainId() => 1;
        public byte GetSubId() => 1;
    }

    public sealed partial class GS2GC_001_001_HeartbeatResponse : Framework.Network.INetMessage
    {
        public byte GetMainId() => 1;
        public byte GetSubId() => 1;
    }

    public sealed partial class GC2GS_001_002_SessionBindRequest : Framework.Network.IRequest<GS2GC_001_002_SessionBindResponse>
    {
        public byte GetMainId() => 1;
        public byte GetSubId() => 2;
    }

    public sealed partial class GS2GC_001_002_SessionBindResponse : Framework.Network.IResponse
    {
        public byte GetMainId() => 1;
        public byte GetSubId() => 2;
    }

}
